name: quay_build_push

on:
  push:
    branches:
      - main

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      reporting-utils: ${{ steps.check-changes.outputs.reporting-utils }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: check-changes
        with:
          filters: |
            reporting-utils:
              - 'reporting-utils/Dockerfile'

  build-push-reporting-utils:
    needs: check-changes
    # if: ${{ needs.check-changes.outputs.reporting-utils == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v5
        with:
          images: quay.io/climb-tre/reporting-utils
          flavor: |
            latest=true
          tags: |
            type=semver,pattern={{version}}
            type=sha
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:reporting-utils"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
